version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - yum install -y jq

  build:
    commands:
      - echo Deploying CloudFormation stack...
      - aws cloudformation deploy \
          --template-file master-stack.yaml \
          --stack-name iac-infras-prod \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides $(cat prod-params.json | jq -r '.[] | "\(.ParameterKey)=\(.ParameterValue)"')

artifacts:
  files:
    - master-stack.yaml
    - prod-params.json
