AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild project using GitHub as source without auto-rebuild on push

Parameters:
  GitHubRepo:
    Type: String

  GitHubBranch:
    Type: String
    Default: main

  GitHubToken:
    Type: String
    NoEcho: true

Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
        - arn:aws:iam::aws:policy/AmazonECS_FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  EcsCicdBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: ecs-cicd-build
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:6.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
      Source:
        Type: GITHUB
        Location: !Sub "https://github.com/${GitHubRepo}.git"
        GitCloneDepth: 1
        BuildSpec: buildspec.yml 
        Auth:
          Type: OAUTH
          Resource: !Ref GitHubToken
        ReportBuildStatus: true
        InsecureSsl: false
      Triggers: 
        Webhook: false
      TimeoutInMinutes: 30

Outputs:
  CodeBuildProjectName:
    Value: !Ref EcsCicdBuild


    


