AWSTemplateFormatVersion: '2010-09-09'
Description: Elastic Beanstalk app with environment

Resources:
  EBApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: MyApp
      Description: My Canary Deploy App

  EBApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref EBApplication
      Description: Initial version
      SourceBundle:
        S3Bucket: my-artifacts-azamcloud
        S3Key: app.zip

  EBEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      EnvironmentName: MyApp-env2
      ApplicationName: !Ref EBApplication
      SolutionStackName: "64bit Amazon Linux 2023 v4.7.1 running PHP 8.4"
      OptionSettings:
        - Namespace: aws:elasticbeanstalk:command
          OptionName: DeploymentPolicy
          Value: RollingWithAdditionalBatch
        - Namespace: aws:elasticbeanstalk:command
          OptionName: BatchSizeType
          Value: Percentage
        - Namespace: aws:elasticbeanstalk:command
          OptionName: BatchSize
          Value: 20
        - Namespace: aws:elasticbeanstalk:command
          OptionName: PauseTime
          Value: PT5M
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: aws-elasticbeanstalk-ec2-role
        - Namespace: aws:autoscaling:asg
          OptionName: MinSize
          Value: 5
        - Namespace: aws:autoscaling:asg
          OptionName: MaxSize
          Value: 10
        - Namespace: aws:autoscaling:asg
          OptionName: DesiredCapacity
          Value: 5

       
      VersionLabel: !Ref EBApplicationVersion
      Tier:
        Name: WebServer
        Type: Standard
