AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  VPCOut:
    Type: String
  PublicSubnet1Out:
    Type: String
  AMI:
    Type: String

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP
      VpcId: !Ref VPCOut
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0 

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMI
      VpcId: !Ref VPCOut
      InstanceType: t3.micro
      SubnetId: !Ref PublicSubnet1Out
      SecurityGroupIds:
        - !Ref SecurityGroup

Outputs:
  SecurityGroupOut:
    Description: A reference to the created VPC
    Value: !Ref SecurityGroup