AWSTemplateFormatVersion: '2010-09-09'
Description: ECR Repository for microservice

Resources:
  MyServiceECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: ecs-cicd-repo
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire untagged images older than 30 days",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 30
                },
                "action": { "type": "expire" }
              }
            ]
          }

Outputs:
  RepositoryUri:
    Value: !GetAtt MyServiceECR.RepositoryUri
