AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Service stack with ALB

Parameters:
  ServiceName:
    Type: String

  ClusterName:
    Type: String

  TaskDefinitionArn:
    Type: String

  PublicSubnet1:
    Type: String
  
  PublicSubnet2:
    Type: String
    
  SG1:
    Type: String

  SG2:
    Type: String

  DesiredCount:
    Type: Number

  ContainerName:
    Type: String

  ContainerPort:
    Type: Number

  VPCID:
    Type: String
    
Resources:

  MyService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref ServiceName
      Cluster: !Ref ClusterName
      LaunchType: FARGATE
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinitionArn
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref PublicSubnet1
            - !Ref PublicSubnet2
          SecurityGroups:
            - !Ref SG1
            - !Ref SG2
      LoadBalancers:
        - ContainerName: !Ref ContainerName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref MyTargetGroup

  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: my-microservices-alb
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref SG1
        - !Ref SG2
      Scheme: internet-facing
      Type: application

  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VPCID
      Protocol: HTTP
      Port: !Ref ContainerPort
      TargetType: ip
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2

  MyListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MyTargetGroup
      LoadBalancerArn: !Ref MyLoadBalancer
      Port: 80
      Protocol: HTTP

Outputs:
  ECSServiceName:
    Description: ECS Service name
    Value: !Ref MyService

  LoadBalancerDNSName:
    Description: Public DNS of the ALB
    Value: !GetAtt MyLoadBalancer.DNSName

  TargetGroupArn:
    Description: ARN of the Target Group
    Value: !Ref MyTargetGroup





