AWSTemplateFormatVersion: '2010-09-09'

Parameters:
#  Environment:
#    Type: String
#
#  VpcCIDR:
#    Type: String
#
#  PublicSubnet1CIDR:
#    Type: String
#
#  PublicSubnet2CIDR:
#     Type: String
#
#  PrivateSubnet1CIDR:
#    Type: String
#
#  PrivateSubnet2CIDR:
#    Type: String
#  AMI:
#    Type: String
#
#  DBUser:
#    Type: String
#
#  DBPassword:
#   Type: String

  TaskFamily:
    Type: String

  ContainerName:
    Type: String

  ContainerPort:
    Type: Number

  Cpu:
    Type: String

  Memory:
    Type: String

  ExecutionRoleArn:
    Type: String

  ImageUrl:
    Type: String

  GitHubRepo:
    Type: String

  GitHubBranch:
    Type: String
    Default: main

  GitHubOwner:
    Type: String

  GitHubToken:
    Type: String

  ClusterName:
    Type: String

  RepoName:
    Type: String

  ServiceName:
    Type: String

  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id

  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id

  SecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>

  DesiredCount:
    Type: Number

  VPCID:
    Type: AWS::EC2::VPC::Id

  
Resources:
#  VPCStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/vpc.yaml
#      Parameters:
#        Environment: !Ref Environment
#        VpcCIDR: !Ref VpcCIDR
#        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
#        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
#        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
#        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
#
#
#
#  EC2Stack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/ec2.yaml
#      Parameters:
#        VPCOut: !GetAtt VPCStack.Outputs.VPCOut
#        PublicSubnet1Out: !GetAtt VPCStack.Outputs.PublicSubnet1Out
#        AMI: !Ref AMI
#
#  RDSStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/rds.yaml
#      Parameters:
#        SecurityGroupOut: !GetAtt EC2Stack.Outputs.SecurityGroupOut
#        PrivateSubnet1Out: !GetAtt VPCStack.Outputs.PrivateSubnet1Out
#        PrivateSubnet2Out: !GetAtt VPCStack.Outputs.PrivateSubnet2Out
#        DBUser: !Ref DBUser
#        DBPassword: !Ref DBPassword
#
#  S3Stack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/s3.yaml
#      Parameters:
#        Environment: !Ref Environment

#  ArtifactBucketStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/artifact-bucket.yaml

#  EBStack:
#   Type: AWS::CloudFormation::Stack
#   Properties:
#     TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/eb.yaml
      
  TaskdefStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/taskdef.yaml
      Parameters:
        TaskFamily: !Ref TaskFamily
        ContainerName: !Ref ContainerName
        ContainerPort: !Ref ContainerPort
        Cpu: !Ref Cpu
        Memory: !Ref Memory 
        ExecutionRoleArn: !Ref ExecutionRoleArn
        ImageUrl: !Ref ImageUrl
  
  CodebuildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/codebuild.yaml
  
  EcsclusterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/ecscluster.yaml
      Parameters:
       ClusterName: !Ref ClusterName

  EcrStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/ecr.yaml
      Parameters:
        RepoName: !Ref RepoName

  EcsServiceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/ecsservice.yaml 
      Parameters:
        ServiceName: !Ref ServiceName
        ClusterName: !Ref ClusterName
        TaskDefinitionArn: !GetAtt TaskdefStack.Outputs.TaskDefinitionArn
        PublicSubnet1: !Ref PublicSubnet1
        PublicSubnet2: !Ref PublicSubnet2
        SecurityGroups: !Ref SecurityGroups
        DesiredCount: !Ref DesiredCount
        ContainerName: !Ref ContainerName
        ContainerPort: !Ref ContainerPort
        VPCID: !Ref VPCID

  CodepipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/codepipeline.yaml
      Parameters:
        GitHubOwner: !Ref GitHubOwner
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch
        GitHubToken: !Ref GitHubToken
        EcsClusterName: !Ref ClusterName
        EcsServiceName: !Ref ServiceName
        CodeBuildProject: !GetAtt CodebuildStack.Outputs.CodeBuildProject
        
    

