AWSTemplateFormatVersion: '2010-09-09'

#Parameters:
#  Environment:
#    Type: String
#
#  VpcCIDR:
#    Type: String
#
#  PublicSubnet1CIDR:
#    Type: String
#
#  PublicSubnet2CIDR:
#     Type: String
#
#  PrivateSubnet1CIDR:
#    Type: String
#
#  PrivateSubnet2CIDR:
#    Type: String
#  AMI:
#    Type: String
#
#  DBUser:
#    Type: String
#
#  DBPassword:
#    Type: String
#
Resources:
#  VPCStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/vpc.yaml
#      Parameters:
#        Environment: !Ref Environment
#        VpcCIDR: !Ref VpcCIDR
#        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
#        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
#        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
#        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
#
#
#
#  EC2Stack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/ec2.yaml
#      Parameters:
#        VPCOut: !GetAtt VPCStack.Outputs.VPCOut
#        PublicSubnet1Out: !GetAtt VPCStack.Outputs.PublicSubnet1Out
#        AMI: !Ref AMI
#
#  RDSStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/rds.yaml
#      Parameters:
#        SecurityGroupOut: !GetAtt EC2Stack.Outputs.SecurityGroupOut
#        PrivateSubnet1Out: !GetAtt VPCStack.Outputs.PrivateSubnet1Out
#        PrivateSubnet2Out: !GetAtt VPCStack.Outputs.PrivateSubnet2Out
#        DBUser: !Ref DBUser
#        DBPassword: !Ref DBPassword
#
#  S3Stack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/s3.yaml
#      Parameters:
#        Environment: !Ref Environment
  
  EBStack:
   Type: AWS::CloudFormation::Stack
   Properties:
     TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/eb.yaml
      

  ArtifactBucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/artifact-bucket.yaml
    
    
