AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Environment:
    Type: String

Resources:
  AppDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Environment}-app-data-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
